### ISSUE TITLE
uniform capitalisation (or not) for text descriptions of questions & answers

### ISSUE THREAD

**Issue by vrooje** [vrooje/gzcandels_datapaper#15]
pick one and stick with it.

**Comment by willettk** [comment]
I'll vote for no capitalization. But agree we (that is, you) should just pick one or the other.

**Comment by vrooje** [comment]
Hmm, I was going to go for whatever was actually in the classification interface. The editor will probably try to change it anyway (like they do with center/centre every time).

**Comment by willettk** [comment]
It's still a grey/gray area. The question text is lowercase: "Is the galaxy
smooth or featured?", but the text on the buttons is uppercase:
["Smooth","Features or disk","Star or artifact"]. So we could pick either.

Both Lintott+11 and Willett+13 use lowercase, FWIW.
