### ISSUE TITLE
Add pie charts to paper

### ISSUE THREAD

**Issue by vrooje** [vrooje/gzcandels_datapaper#26]
I'm thinking we should start the "Use of classifications in practice" section with this, as in "this is overall, but it contains no appropriate selections on redshift, luminosity, mass, etc.; here's what you do if you want to do a specific study".

What do you think? @willettk

**Comment by willettk** [comment]
Yes - very good idea. I'll try to put in an outline of this, but we should work together if there are any specific cutoffs you've found useful (ref those used in Simmons+ CANDELS bars, for example).

**Comment by willettk** [comment]
Closed with 2a98f635ec172003ae424b53239ab2a60d4e51f0.
