### ISSUE TITLE
Upper limits on p-values in Section 4

### ISSUE THREAD

**Issue by willettk** [vrooje/gzcandels_datapaper#31]
We quote a lot of p-values in Section 4 for the CANDELS team-GZ comparisons. I think an upper limit (p < 2e-16) is more appropriate than putting p~0, since posterity won't necessarily know what our machine precision was.

**Comment by vrooje** [comment]
Yeah, there's some discussion of this in various stats stackexchange type places. Python (which I used instead of R) was reporting things like p = 2.3e-147 and such, which is obviously a bit weird. Didn't I footnote the first p-value with an explanation though?

Speaking of which, I wanted to footnote that with a symbol instead of a number as it looked like I was taking 0 to the 4th power.

**Comment by willettk** [comment]
Right - I missed the footnote.

I agree that 10**-147 is essentially zero, but we might still want to
report the limit (or some upper bound). I also can't really believe that
Python is truly that accurate - what do the stats people say about that?

**Comment by vrooje** [comment]
I can dig up the link again, but basically if you're really worried about distinctions between super-low and super-super-low p values, there's a different method you have to use. In our case I think that's overkill as we're basically saying it's >5 sigma.

**Comment by willettk** [comment]
I'm not really concerned in the slightest as far as our science results go.
The difference between super super low and super**3 low isn't meaningful
for us. I just eyeroll whenever I see phrases like "statistically
significant" or "p~0" in other papers without actual numbers attached. Was
hoping to have something in the footnote that indicates our actual
quantitative level, or at least an upper limit.

**Comment by vrooje** [comment]
Yeah, fair enough - and the distinction between the first 3 reported values, which actually did report p=0.0, and the fourth, which reported p=3.64e-122, is pretty silly anyway. I should just report them all as closer to 0 than machine precision.

**Comment by willettk** [comment]
Good by me. Closed by https://github.com/vrooje/gzcandels_datapaper/commit/e453bc6578e96b2bf1b23072020292611a67d506.
