### ISSUE TITLE
Discussion of resolution issues

### ISSUE THREAD

**Issue by vrooje** [vrooje/gzcandels_datapaper#35]
There isn't one, and there should be. At what redshifts are we resolving what features? What constraints does a "smooth" classification put on feature sizes? For extended sources, what does a plot of size versus p_artifact look like?

**Comment by chrislintott** [comment]
A note to say that it would be good to frame this in the context of future surveys; can we say something about what redshift Euclid will get reliable morphologies, for example?

**Comment by vrooje** [comment]
@karenlmasters Euclid will be about half the resolution of HST, right? Any particular reference I should use?

**Comment by karenlmasters** [comment]
Yes about that. I have the exact figure somewhere if you need me to look it
up.

Karen.

**Comment by vrooje** [comment]
Have come back to this now and I'm having trouble finding The Obvious Reference to use for EUCLID. Right now I'm planning to go with [Content (2008)](https://ui.adsabs.harvard.edu/#abs/2008SPIE.7010E..25C/abstract), which describes the optical design, and [Beaulieu et al. (2010)](https://ui.adsabs.harvard.edu/#abs/2010ASPC..430..266B/abstract), which seems more general. Does that sound right @karenlmasters?

I'm wondering at the word "reliable" used by @chrislintott above. I'm not exactly sure what that means but I'm more comfortable talking about "comparable", as in, at what redshifts EUCLID will go beyond our worst resolution...

**Comment by vrooje** [comment]
Nevermind, I'd only read the abstract of Beaulieu et al... it seems to be only about microlensing (despite the abstract) so it appears it isn't the right ref.

**Comment by vrooje** [comment]
@karenlmasters can you confirm I should use [Refregier et al. (2010)](https://ui.adsabs.harvard.edu/#abs/2010arXiv1001.0061R/abstract)?

**Comment by karenlmasters** [comment]
I'm sorry I'm so rubbish at responding to these. Apparantly I'm not quite
into github collaboration yet.... I'll work on it.

Karen.
