### ISSUE TITLE
Figure 6: stack 2D plots? interactive 3D plots?

### ISSUE THREAD

**Issue by vrooje** [vrooje/gzcandels_datapaper#39]
The current F6 is not successful at convincing people of the quality of fits to \Delta f_value as a function of f_value and surface brightness. A simple fix is to just plot the planes as two line plots for each response (and probably include fewer responses), but we could explore having interactive 3D plots (which apparently MNRAS supports). Does anyone know how to do this? @willettk @rjsmethurst @chrislintott @CKrawczyk etc? 

If not I'm tempted to just do the 2 2D plots because I don't want to get bogged down in this.

**Comment by willettk** [comment]
Haven't tried myself, although it seems like an interesting Hack Day event. I remember seeing this paper that did one of the better jobs of presenting a 3D plot. 

http://iopscience.iop.org/article/10.1088/0004-637X/793/2/127/meta

Actual plot: http://dx.doi.org/10.1088/0004-637X/793/2/127/data
