### ISSUE TITLE
Need and example figure with colour?

### ISSUE THREAD

**Issue by karenlmasters** [vrooje/gzcandels_datapaper#45]
Early on Fig 4 is referenced as showing the colour images. It doesn't. Also you can't point to Fig 4 before Fig 1, 2, 3. MNRAS won't allow it....

**Comment by willettk** [comment]
I think the Figure 4 examples are color (inverted palette)? The color
contrast really isn't very big in these bands.

**Comment by karenlmasters** [comment]
Oh yes you are quite right. Obvious now you say it. Still can't reference it first though. :( 

Karen.

**Comment by vrooje** [comment]
Hmm, okay, I can take out that early reference...

**Comment by vrooje** [comment]
removed in 002b002a61a71932ffcf6eca0671e143e6685ecd
