### ISSUE TITLE
Histogram of number of classifications per user

### ISSUE THREAD

**Issue by karenlmasters** [vrooje/gzcandels_datapaper#46]
Would it make sense to add a histogram of number of classifications per user in Section 3.3? I like to show those in talks....

**Comment by willettk** [comment]
Did you want a histogram specifically, beyond the information in Figure 2b?

**Comment by karenlmasters** [comment]
I found myself wanting one, but that might just be me.....

**Comment by vrooje** [comment]
I can make that easily enough, but it's not new information from Fig 2b... I know that's a slightly unusual way to show a distribution, but it's the best visualisation for the Gini coefficient so I decided to go with that one even if it's a little outside the astronomer comfort zone...
