### ISSUE TITLE
Should we put the missing wide depth images of the deep sample on the site? 

### ISSUE THREAD

**Issue by karenlmasters** [vrooje/gzcandels_datapaper#49]
In Section 3.8 we say that we do not have wide-field depth classifications for 8130 subjects with deep exposures. We could collect them.... Should we?

**Comment by vrooje** [comment]
I think we could do it for a future data release paper... does this suggestion mean you're concerned the depth correction section is weak?

**Comment by vrooje** [comment]
I think we could add this as a potential to-do for the main Galaxy Zoo repository, but it won't go into this paper.
