### ISSUE TITLE
smooth_disks as flag in catalog, not separate table

### ISSUE THREAD

**Issue by vrooje** [vrooje/gzcandels_datapaper#53]
I suspect the referee will dislike Table 5 as much as I do now that I'm in the post-submission clarity phase. Since we aren't publishing B/Tot ratios in this paper (those are for @BorisHaeussler to publish as he sees fit), those galaxies should just be identified via a flag in the main catalog.

**Comment by willettk** [comment]
Agreed; just change after ref. report
